name: Metrics

on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
    # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]} # remove "master" from array

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Github Metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@v3.28
        with:
          token: ${{ secrets.MECTRICS_TOKEN }}
          filename: github-metrics.svg
          config_timezone: Europe/Brussels
          base: base_indepth, activity, metadata
          plugin_isocalendar: no
          plugin_languages: yes
          plugin_habits: no
          plugin_habits_facts: no
          plugin_habits_charts: no
          repositories_forks: no
          plugin_followup: no
          plugin_gists: no
          plugin_lines: no

